### ISSUE TITLE
Add sunsetdata.csv

### ISSUE THREAD

**Issue by cyclops1982** [timelapseplus/TimelapsePlus-Firmware#25]
Hi,

The file sim.html uses a sunsetdata.csv file, but this file is not checked into GIT and therefor sim.html does not seem to work.

I think there are some people who would be very willing to contribute to this project, but the lack of support for this makes it very difficult. I know this probably is a side-project for you, but i think people bought hardware and want to play and improve on it! :)

**Comment by elijahparker** [comment]
sorry about that!  I just added it now. Apparently I had moved it to the server during development and the code in the repo was left incomplete.  I copied the full server code back into the repo.  Here's where it's published live: http://firmware.timelapseplus.com/sunset/
